version: 1
labels:
  - label: "feature"
    title: "Feature.*"
  - label: "bug"
    title: "Bug.*"
  - label: "chore"
    title: "Chore.*"
  - label: "tooling"
    title: "Tooling.*"
  - label: "feature"
    branch: "^feature/.*"
  - label: "bug"
    branch: "^bug/.*"
  - label: "chore"
    branch: "^chore/.*"
  - label: "tooling"
    branch: "^tooling/.*"
