name: Bump Version
on:
  pull_request:
    branches:
      - "main"
    types: [closed]

jobs:
  bump:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # major:minor:patch
          custom_tag: ${{contains(github.event.pull_request.labels.*.name, 'major') && 'major' || contains(github.event.pull_request.labels.*.name, 'minor') && 'minor' || contains(github.event.pull_request.labels.*.name, 'patch') && 'patch' || 'patch'}}
