name: Bump Version
on:
  pull_request:
    branches:
      - main
  types: [closed]

jobs:
  bump:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
# if: contains(github.event.pull_request.labels.*.name, 'some-defined-label')a
