name: "Main Merge"
on:
  push:
    branches:
      - development

jobs:
  create-pr-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0

      - uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          title: ":tada: main merge"
